### ISSUE TITLE
fail on r-devel

### ISSUE THREAD

**Issue by alkodsi** [Bioconductor/GenomicAlignments#10]
I have developed a package that uses GenomicAlignments and I am trying to submit my package to cran. However, the tests on  r-devel-windows-ix86+x86_64 are failing with a backtrace that points to GenomicAlignments::readGAlignments. Can you please help?

My package: 
https://github.com/alkodsi/ctDNAtools

The error:
 test_check("ctDNAtools")
    -- 1. Error: (unknown) (@test-ctDNAtest.R#13)  ---------------------------------
    trying to get slot "className" from an object of a basic class ("character") with no slots
    Backtrace:
      1. ctDNAtools::test_ctDNA(...)
      2. ctDNAtools::get_mutations_read_names(...)
      3. purrr::pmap(...)
      4. ctDNAtools:::.f(...)
      5. ctDNAtools:::get_mutation_read_names(...)
      6. GenomicAlignments::stackStringsFromBam(...)
      8. GenomicAlignments::readGAlignments(...)
     10. GenomicAlignments::readGAlignments(...)
     11. GenomicAlignments:::.bindExtraData(...)
     15. methods::is(listData[[1L]], getClass("Annotated"))

**Comment by lshep** [comment]
Can you provide a smaller reproducible example?  It would be hard to reproduce this without digging into your package and test code to find where and how you ran this.  Please also provide your `sessionInfo( )`

**Comment by alkodsi** [comment]
Thank you for the quick response. I am out of office for two weeks unfortunately. 
For now I can only provide that my package unit tests are failing only on win-builder (dev version): https://win-builder.r-project.org/

You can try to run GenomicAlignments unit tests on win-builder and see if something broke in the dev version. If that works, you can try readGAlignments() on one of the bam files in my package, put it in a unit test and send it to win-builder.

Googling the error also shows that several cran packages (related to genomics) are failing tests on the dev version with the same error, so I am suspecting that it is not related to my package in particular. 

Sorry that I can't do more at the moment. I can be more exact in two weeks.

Here is the full log:

Flavor: r-devel-windows-ix86+x86_64
Check: running tests for arch 'i386', Result: ERROR
    Running 'testthat.R' [12s]
  Running the tests in 'tests/testthat.R' failed.
  Complete output:
    > library(testthat)
    > library(ctDNAtools)
    >
    > test_check("ctDNAtools")
    -- 1. Error: (unknown) (@test-ctDNAtest.R#13)  ---------------------------------
    trying to get slot "className" from an object of a basic class ("character") with no slots
    Backtrace:
      1. ctDNAtools::test_ctDNA(...)
      2. ctDNAtools::get_mutations_read_names(...)
      3. purrr::pmap(...)
      4. ctDNAtools:::.f(...)
      5. ctDNAtools:::get_mutation_read_names(...)
      6. GenomicAlignments::stackStringsFromBam(...)
      8. GenomicAlignments::readGAlignments(...)
     10. GenomicAlignments::readGAlignments(...)
     11. GenomicAlignments:::.bindExtraData(...)
     15. methods::is(listData[[1L]], getClass("Annotated"))

    -- 2. Error: (unknown) (@test-fragment_size.R#13)  -----------------------------
    trying to get slot "className" from an object of a basic class ("character") with no slots
    Backtrace:
      1. ctDNAtools::get_fragment_size(bamN3)
      3. GenomicAlignments::readGAlignmentPairs(file = bam, param = sbp)
      5. GenomicAlignments::readGAlignmentPairs(...)
      7. GenomicAlignments::readGAlignments(...)
      8. GenomicAlignments:::.bindExtraData(...)
     12. methods::is(listData[[1L]], getClass("Annotated"))

**Comment by hpages** [comment]
Looks like you ran into the [following issue](https://github.com/Bioconductor/S4Vectors/issues/58) which has been fixed in ~S4Vectors~ **R-devel** since then. All you need to do is resubmit your package to win-builder and cross your fingers that ~win-builder is using the latest version of S4Vectors (0.25.12 at the moment)~ the problem will go away (it should be using the latest version of R-devel).

Thanks!

**Comment by alkodsi** [comment]
@hpages Many thanks. It is working now as you expected.
