### ISSUE TITLE
S4Vectors

### ISSUE THREAD

**Issue by jiangweixia** [Bioconductor/GenomicAlignments#14]
sorry, I have a question, 

when I installed the package in R 4.0.2, it was wrong with the S4Vectors 0.26.1 but need to >=0.27.12, how to solve this question?

Thanks

**Comment by lshep** [comment]
What is your `sessionInfo()`  and `BiocManager::valid()` ?

Using version number x.y.z, 
An even y indicates a package in release while an odd y indicates a package in devel.  You may need to [update to use devel]( http://bioconductor.org/developers/how-to/useDevel/)
