### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by shiyi-pan** [Bioconductor/GenomicAlignments#15]
Hi, I  trid to install the package and met an error. My OS is Red Hat and GCC vresion is 8.3.0 and the package version is  GenomicAlignments_1.10.1.  I can't install the new version because of the limit of Rsamtools vresion  could you help me fix this problem ? Thank you very much .

encodeOverlaps_methods.c: In function 'CharAE_append_int':
encodeOverlaps_methods.c:49:2: warning: implicit declaration of function 'append_string_to_CharAE' [-Wimplicit-function-declaration]
  append_string_to_CharAE(char_ae, buf);
  ^~~~~~~~~~~~~~~~~~~~~~~
gcc -std=gnu99 -shared -fPIC -L/ds3512/home/panyp/ruanjian/packages/lib -o GenomicAlignments.so IRanges_stubs.o R_init_GenomicAlignments.o S4Vectors_stubs.o cigar_utils.o coordinate_mapping_methods.o encodeOverlaps_methods.o
installing to /ds3512/home/panyp/ruanjian/R-4.0.3/lib64/R/library/00LOCK-GenomicAlignments/00new/GenomicAlignments/libs
** R
** inst
** byte-compile and prepare package for lazy loading
Warning: undefined slot classes in definition of "GAlignments": NAMES(class "characterORNULL")
Error in rematchDefinition(definition, fdef, mnames, fnames, signature) :
  methods can add arguments to the generic 'seqinfo<-' only if '...' is an argument to the generic
Error: unable to load R code in package 'GenomicAlignments'
Execution halted
ERROR: lazy loading failed for package 'GenomicAlignments'
* removing '/ds3512/home/panyp/ruanjian/R-4.0.3/lib64/R/library/GenomicAlignments'

**Comment by mtmorgan** [comment]
Make sure that your installation is correct
```
BiocManager::valid()
```
