### ISSUE TITLE
BiocParallel errors

### ISSUE THREAD

**Issue by gevro** [Bioconductor/GenomicAlignments#18]
Hi,
I'm getting this error when running readGAlignments on a BamViews object as follows:
readGAlignments(bamfiles,param=ScanBamParam(what=scanBamWhat(),tag=c("rq")),with.which_label=TRUE)

Error: BiocParallel errors
  2 remote errors, element index: 1, 2
  0 unevaluated and other errors
  first remote error: cannot coerce class "list" to a DataFrame
In addition: Warning messages:
1: In readGAlignments(bamfiles, param = ScanBamParam(what = scanBamWhat(),  :
  'bamRanges(file)' and 'bamWhich(param)' differ; using 'bamRanges(file)'
2: stop worker failed:
  wrong args for environment subassignment

**Comment by gevro** [comment]
The error seems to occur when I try to load a tag of this type: "xx:B:C" with param=ScanBamParam(tag=c("xx")), where xx is the tag of type "B:C".

My guess is that readGAlignments cannot handle tag arrays? However, I didn't see this in the documentation.

**Comment by LiNk-NY** [comment]
Hi @gevro 
Can you please provide a reproducible example? 
Best regards,
Marcel

**Comment by hpages** [comment]
@gevro We can't help you without a reproducible example. Feel free to re-open this issue if you decide to follow up on this.
