### ISSUE TITLE
Differences in reads' base content with IGV.

### ISSUE THREAD

**Issue by sfragkoul** [Bioconductor/GenomicAlignments#30]
Hey there and thanks for the amazing package, it's been really helpful!

I stumbled upon an issue which I would like to share with you.
So I have generated a synthetic bam file using [NEAT](https://github.com/ncsa/NEAT) that contains reads in the TP53 region (it's located in the 17th chromosome and spans for about 19k bases).
My interest is to benchmark the somatic variants which are produced by [GATK-Mutect2](https://gatk.broadinstitute.org/hc/en-us/articles/360037593851-Mutect2) and to do that I need to know exactly the Allele Frequencies (AF) of the variants and hence the number of all bases in each chromosomal position.

To my great surprise I found that at certain chromosomal positions, although the coverage is correct, the reported bases do differ!
Below I present the lines of code that I am using in R with the help of "GenomicAlignments" library.

```   
library(GenomicAlignments)

bam = scanBam("1/1_golden.bam")

#Read genomic alignments
olaps <- readGAlignments("1/1_golden.bam")

#chromosomal position
p=474

# reads in chromosomal position
index = which(start(olaps) <= p & end(olaps) >= p)

#extract reads from bam
my_seqs = bam[[1]]$seq[index]

#distance from position p
ret = p - start(olaps[index, ]) + 1

out = mapply(function(x, y) {
    
    str_sub(x, y, y)
    
}, as.character(my_seqs), ret)


out = data.table(
    "base" = out
)

out = out[, by = base, .N] 

```

I am also attaching a print screen.
![IGV](https://github.com/Bioconductor/GenomicAlignments/assets/79847870/83f7ab66-5025-4814-8061-eac8ef9eb0d4)

On the left you see the ``` out ``` parameter which contains the bases from the chromosomal position ``` p ``` (in this case ``` p=474 ```) and on the right you see the info as produced by [IGV ](https://software.broadinstitute.org/software/igv/)for the same position ``` p ```. The coverage is the same (478 in both cases), the difference is found in the base content of the reads.

I am very curious to see what causes this systematic deviation between IGV and my code. If anyone has faced this problem before or has any clue, I would really appreciate it!

Thanks in advance,
Stella

**Comment by sfragkoul** [comment]
hello again.

After digging into the problem, it turns out that the source of this misalignment are the indels and how each algorithm treats them.

Sorry for bothering you :)

**Comment by hpages** [comment]
No worries. Glad you figured it out.
